-- BOLETÍN 4-3 NESQUICK

-- drop database ACTIVIDADES_DEPORTIVAS;

-- 1
CREATE DATABASE IF NOT EXISTS ACTIVIDADES_DEPORTIVAS;
USE ACTIVIDADES_DEPORTIVAS;

CREATE TABLE SALA (
	Cod_sala INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(20) NOT NULL,
    Tamano DECIMAL(5,2) NOT NULL COMMENT "Metros cuadrados"
);

CREATE TABLE ACTIVIDAD (
	Cod_Act INT UNSIGNED NOT NULL PRIMARY KEY AUTO_INCREMENT,
    Nombre VARCHAR(20) NOT NULL,
    Temporada ENUM("Verano", "Invierno") NOT NULL,
    Descripcion VARCHAR(400)
);

CREATE TABLE MONITOR (
	DNI CHAR(9),
    Nombre VARCHAR(30) NOT NULL,
    Telef_contacto VARCHAR(15) NOT NULL COMMENT "Teléfono con prefijo internacional, empezando con un '+', p.ej: +3465757675, sin campos en blanco",
    Especialidad ENUM("Tenis", "Badminton", "Padel", "Frontenis", "Squash") NOT NULL,
    CONSTRAINT ACTIVIDAD_PK
		PRIMARY KEY (DNI)
);

CREATE TABLE conduce (
	Cod_sala INT UNSIGNED,
    DNI_monitor CHAR(9),
    Cod_Act INT UNSIGNED,
    Fecha DATE NOT NULL,
    Hora_Inicio TIME NOT NULL,
    Hora_fin TIME NOT NULL,
    CONSTRAINT conduce_PK
		PRIMARY KEY (Cod_Sala, DNI_monitor,Cod_Act,Fecha,Hora_inicio),
	CONSTRAINT conduce_FK_SALA
		FOREIGN KEY (Cod_Sala) REFERENCES SALA(Cod_sala)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	CONSTRAINT conduce_FK_MONITOR
		FOREIGN KEY (DNI_monitor) REFERENCES MONITOR(DNI)
			ON DELETE CASCADE
            ON UPDATE CASCADE,
	CONSTRAINT conduce_FK_ACTIVIDAD
		FOREIGN KEY (Cod_Act) REFERENCES ACTIVIDAD(Cod_Act)
			ON DELETE CASCADE
            ON UPDATE CASCADE
);
    
    
-- Ejercicio 2
CREATE DATABASE IF NOT EXISTS MONTAXE_DE_COCINAS;
USE MONTAXE_DE_COCINAS;

CREATE TABLE CLIENTE (
	cod_cliente INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(30) NOT NULL
);

CREATE TABLE EMPLEADO (
	DNI CHAR(9) PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    fecha_inicio_contrato DATE NOT NULL,
    fecha_fin_contrato DATE NOT NULL
);
    

CREATE TABLE DISENADOR (
	DNI CHAR(9) PRIMARY KEY,
    CONSTRAINT DISENADOR_FK_EMPLEADO
		FOREIGN KEY (DNI) REFERENCES EMPLEADO(DNI)
			ON DELETE CASCADE
            ON UPDATE CASCADE
);


CREATE TABLE MONTADOR (
	DNI CHAR(9) PRIMARY KEY,
    cod_montador CHAR(9) UNIQUE COMMENT "Combinación única de letras y números para cada montador",
    CONSTRAINT MONTADOR_FK_EMPLEADO
		FOREIGN KEY (DNI) REFERENCES EMPLEADO(DNI)
			ON DELETE CASCADE
            ON UPDATE CASCADE
);



CREATE TABLE COCINA (
	cod_cocina INT PRIMARY KEY AUTO_INCREMENT,
	estructura VARCHAR(30) NOT NULL,
    material ENUM("Mármol","Madera","Piedra") NOT NULL,
    colores SET("Blanco","Azul","Verde Pimiento") NOT NULL,
	cod_cliente INT NOT NULL,
    pagado ENUM("S","N") NOT NULL COMMENT "S para pagado y N para no pagado",
    DNI_disenador CHAR(9) NOT NULL,
    CONSTRAINT COCINA_FK_DISENADOR
		FOREIGN KEY (DNI_disenador) REFERENCES DISENADOR(DNI)
			ON DELETE CASCADE
            ON UPDATE CASCADE
);

CREATE TABLE ELECTRODOMESTICO (
	codigo INT PRIMARY KEY AUTO_INCREMENT,
	tipo ENUM("Lavadora","Lavavajillas","Vitrocerámica") NOT NULL,
    marca ENUM("Teka","Samsumg","Balay") NOT NULL
);

CREATE TABLE PREFIERE (
	cod_cliente INT,
    DNI_disenador CHAR(9),
    CONSTRAINT PREFIERE_PK
		PRIMARY KEY (cod_cliente, DNI_disenador),
	CONSTRAINT PREFIERE_FK_CLIENTE
		FOREIGN KEY (cod_cliente) REFERENCES CLIENTE(cod_cliente)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	CONSTRAINT PREFIERE_FK_DISENADOR
		FOREIGN KEY (DNI_disenador) REFERENCES DISENADOR(DNI)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);


CREATE TABLE MONTA_MUEBLE (
	cod_cocina INT,
    DNI_montador CHAR(9),
    fecha DATE,
    hora_inicio TIME,
    hora_fin TIME NOT NULL,
	CONSTRAINT MONTA_MUEBLE_PK
		PRIMARY KEY (cod_cocina, DNI_montador, fecha, hora_inicio),
	CONSTRAINT MONTA_MUEBLE_FK_COCINA
		FOREIGN KEY (cod_cocina) REFERENCES COCINA(cod_cocina)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	CONSTRAINT MONTA_MUEBLE_FK_MONTADOR
		FOREIGN KEY (DNI_montador) REFERENCES MONTADOR(DNI)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

CREATE TABLE MONTA_ELECTRODOMESTICO (
	cod_cocina INT,
    cod_electrodomestico INT,
    DNI_montador CHAR(9) NOT NULL,
    CONSTRAINT MONTA_ELECTRODOMESTICO_PK
		PRIMARY KEY (cod_cocina, cod_electrodomestico),
	CONSTRAINT MONTA_ELECTRODOMESTICO_FK_COCINA
		FOREIGN KEY (cod_cocina) REFERENCES COCINA(cod_cocina)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	CONSTRAINT MONTA_ELECTRODOMESTICO_FK_ELECTRODOMESTICO
		FOREIGN KEY (cod_electrodomestico) REFERENCES ELECTRODOMESTICO(codigo)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	CONSTRAINT MONTA_ELECTRODOMESTICO_FK_MONTADOR
		FOREIGN KEY (DNI_montador) REFERENCES MONTADOR(DNI)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);
	
    
-- 3
CREATE DATABASE IF NOT EXISTS DIAGNOSTICOS_MEDICOS;
USE DIAGNOSTICOS_MEDICOS;

CREATE TABLE PACIENTE (
	NSS CHAR(12) PRIMARY KEY,
    nombre VARCHAR(30) NOT NULL,
    apelidos VARCHAR(30) NOT NULL,
    DNI CHAR(9) NOT NULL UNIQUE,
    fecha_nacimiento DATE NOT NULL
);


CREATE TABLE HISTORIAL (
	numero_historial CHAR(9) COMMENT "Código único formado por 9 letras y números)" PRIMARY KEY,
    tratamientos VARCHAR(9) NOT NULL,
    NSS_paciente CHAR(12) NOT NULL,
    CONSTRAINT HISTORIAL_FK_PACIENTE
		FOREIGN KEY (NSS_paciente) REFERENCES PACIENTE(NSS)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

CREATE TABLE DIAGNOSTICO (
	codigo_diagnostico CHAR(9) COMMENT "Código de 9 letras y números" PRIMARY KEY,
    descripcion VARCHAR(200)
);

CREATE TABLE MEDICO (
	codigo_medico INT PRIMARY KEY AUTO_INCREMENT,
    nombre VARCHAR(30) NOT NULL,
    apelidos VARCHAR(30) NOT NULL
);


CREATE TABLE RESIDENTE (
	codigo_medico INT PRIMARY KEY,
    CONSTRAINT RESIFENTE_FK_MEDICO
		FOREIGN KEY (codigo_medico) REFERENCES MEDICO(codigo_medico)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);

CREATE TABLE TITULAR (
	codigo_medico INT PRIMARY KEY,
    especialidad ENUM("urologia","psiquiatria"),
    CONSTRAINT TITULAR_FK_MEDICO
		FOREIGN KEY (codigo_medico) REFERENCES MEDICO(codigo_medico)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);
    

CREATE TABLE DICTA (
	NSS_paciente CHAR(12),
    codigo_diagnostico CHAR(9),
    codigo_medico_titular INT,
    fecha DATE NOT NULL,
    CONSTRAINT DICTA_PK
		PRIMARY KEY (NSS_paciente, codigo_diagnostico, codigo_medico_titular),
	CONSTRAINT DICTA_FK_PACIENTE
		FOREIGN KEY (NSS_paciente) REFERENCES PACIENTE(NSS)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	CONSTRAINT DICTA_FK_DIAGNOSTICO
		FOREIGN KEY (codigo_diagnostico) REFERENCES DIAGNOSTICO(codigo_diagnostico)
			ON DELETE CASCADE
			ON UPDATE CASCADE,
	CONSTRAINT DICTA_FK_TITULAR
		FOREIGN KEY (codigo_medico_titular) REFERENCES TITULAR(codigo_medico)
			ON DELETE CASCADE
			ON UPDATE CASCADE
);
    
    
    
    
    
    